return {
	-- "ATT items",
	"WPN_Zariel_Flail",
	"WPN_Zariel_Hammer",
	"MOD_WPN_Ranseur",
	"MOD_Prism_Helper_Invisible_A",
	"MOD_Plantear_Greatsword_B",
	"MOD_Meteor_Helper_Invisible_A",
	"MOD_Eladrin_Longbow",
	"MOD_Irenicus_Mace",
	"MOD_Erinyes_Bow",
	"MOD_Erinyes_Longsword",
	"MOD_Runepowder_Time_Bomb",
	"MOD_Runepowder_Vial_Thrown",
	"MOD_RuneVial",
	"LOOT_Throwable_Spell_DelayedBlastFireball",
	"MOD_Whirlwind_Helper",
	"MOD_RevGrav_Helper_Invisible_A",
	"MOD_Helper_Spell_IncendiaryCloud",
	"MOD_Helper_Spell_MaddeningDarkness",
	"MOD_DelayedFireball_Helper_Invisible_A",
	"MOD_Solar_Bow",
	"MOD_Solar_Greatsword",
	"MOD_Icingdeath",
	"MOD_Twinkle",
	"MOD_Drizzt_Scimitar1",
	"MOD_Drizzt_Scimitar2",
}
